services:
  ollama:
    image: ollama/ollama:0.3.10-rocm
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=10.3.0'
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

  webui:
    image: ghcr.io/open-webui/open-webui:v0.3.21
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    ports:
      - 8080:8080
    volumes:
      - ./webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
